### ISSUE TITLE
Fast version of UUID v7

### ISSUE THREAD

**Issue by marcotama** [f4b6a3/uuid-creator#100]
Hello!

This is a feature request.

Could you add a fast (i.e. non-cryptographic) version of UUID v7, same as you have for v4?

**Comment by fabiolimace** [comment]
Hi @marcotama !

I like the idea, but I don't plan on adding more features soon.

However, you can do the following.

Use [GUID](https://github.com/f4b6a3/uuid-creator/blob/master/src/main/java/com/github/f4b6a3/uuid/alt/GUID.java) alternative:

```java
UUID uuid = GUID.v7().toUUID();
```

Or use the [v7 factory](https://github.com/f4b6a3/uuid-creator/blob/master/src/main/java/com/github/f4b6a3/uuid/factory/rfc4122/TimeOrderedEpochFactory.java) directly:

```java
TimeOrderedEpochFactory v7 = TimeOrderedEpochFactory.builder().withFastRandom().build(); // for reuse
UUID uuid = v7.create();
```

The first option is extremely fast because it is very simple as you can see in the [source code](https://github.com/f4b6a3/uuid-creator/blob/aab6c0e1541c52706f1b15d27ce496eebed9bcb9/src/main/java/com/github/f4b6a3/uuid/alt/GUID.java#L327).

The second option is a faster version of `UuidCreator.getTimeOrderedEpoch()`, that is, with the same implementation, except for the random generator.

**Comment by marcotama** [comment]
Hi @fabiolimace , thank you for the reply! I did not know about this API, that's perfect for my needs. It might be worth adding it to the README, maybe? Regardless, thank you for making this library!

**Comment by fabiolimace** [comment]
I just updated the README to better explain the new GUID API.

I won't mention `TimeOrderedEpochFactory` because there are already some examples on the [Wiki pages](https://github.com/f4b6a3/uuid-creator/wiki/1.7.-UUIDv7).
