### ISSUE TITLE
New algorithm sequential uuid ?

### ISSUE THREAD

**Issue by bflorat** [f4b6a3/uuid-creator#14]
What about a new non-standard algorithm :
sequential uuid generator ?

See https://www.2ndquadrant.com/en/blog/sequential-uuid-generators/

It is database friendly like COMB but has some advantages : 

- full timestamp stored as prefix/suffix creates security leak about time of generation. This new algorithm is a rolling value over 2 bytes, so it has not this problem
-  Risk of collision is far thinner using this algorithm as we still have 14 bytes of random bytes over 16 and not 10 over 16 with COMB.

A running code is available at https://gist.github.com/bflorat/d7d152059b65844531b3c69e4438d00e  

(credit : original code at https://gist.github.com/zenios/72dfaf3a931ad0e4e5e7031d950c3d9c but doesn't work)

**Comment by fabiolimace** [comment]
@bflorat ,

I renamed the COMB generators to prevent confusion:

* `AltCombGuidCreator` -> `PrefixCombCreator`
* `CombGuidCreator` -> `SuffixCombCreator`

I also implemented the sequential UUID generator proposed by Vondra with these names:

* `ShortPrefixCombCreator`
* `ShortSuffixCombCreator`

The reason why I called them as "COMBs" is that they are also _combinations_ of time and random bytes. The main difference is the number of bytes reserved for timestamp. In the new generators the prefix/suffix uses only 2 bytes, instead of 6 bytes in the original COMB.

A new version will be released if you approve these changes and additions. Please, check the last commit 11a61a83d584b17466a7513eb9414ca20690c008 and read the sections related to COMBs in `README.md`.

Thank you!

**Comment by bflorat** [comment]
Thanks a lot, this is good for me.

Performances are pretty good (1 microsec / call of UuidCreator.getShortPrefixComb() on my old quad-cores 2.4Ghz).

Names are fine.

Please release it and update Maven central.

KUTGW

**Comment by fabiolimace** [comment]
Thank you so much!

**Comment by fabiolimace** [comment]
Version 2.2.0 released. In the next few hours will be on Maven central.

**Comment by bflorat** [comment]
Great ! Many thanks.
