### ISSUE TITLE
Deprecation of name-based methods with a UUID name parameter

### ISSUE THREAD

**Issue by ahjohannessen** [f4b6a3/uuid-creator#91]
Hi @fabiolimace 

I wondered why the name-based methods with a UUID name parameter are being deprecated?

We use it to derive deterministic UUIDs.

**Comment by fabiolimace** [comment]
Hi @ahjohannessen 

Apologies for the delay.

The methods were deprecated for three reasons:
* RFC-4122 does not explicitly state that the name parameter could be another UUID;
* No other implementation offers a method with a name parameter with UUID type;
* If someone needed this, he or she could use the [`ByteBuffer`](https://www.baeldung.com/java-bytebuffer) or [`BinaryCodec`](https://github.com/f4b6a3/uuid-creator/blob/master/src/main/java/com/github/f4b6a3/uuid/codec/BinaryCodec.java) class to transform the UUID into a byte array.

I thought no one was using these methods because they were so unusual. I couldn't find any use of these methods here on Github.

However, now that I know someone is using them, I no longer intend to deprecate them. On the contrary, I'm happy that this library is being useful. Thanks for keeping me from breaking the golden rule of public interfaces!

Soon, I will release a patch version that undoes deprecation.

**Comment by ahjohannessen** [comment]
Thanks for your answer :) We changed our code to use uuid.toString, but good to know the reasoning behind the deprecation.

**Comment by fabiolimace** [comment]
Hi @ahjohannessen !

I just want to let you know that I changed my mind again.

The methods with UUID as the name parameter **will continue deprecated**.

Before the removal, UUIDs can be used as the name parameter like this:

```java
UUID hashed = UuidCreator.getNameBasedMd5(uuid);
```

In the future, after the removal, you'll have to add a statement using `ByteBuffer` to convert the UUID into a byte array:

```java
byte[] name = ByteBuffer.allocate(16)
                .putLong(uuid.getMostSignificantBits())
                .putLong(uuid.getLeastSignificantBits())
                .array();
UUID hashed = UuidCreator.getNameBasedMd5(name);
```

Alternatively, you can add a single line using `BinaryCodec` which is as efficient as the current method implementation, doing the same as `ByteBuffer`:

```java
byte[] name = BinaryCodec.INSTANCE.encode(uuid);
UUID hashed = UuidCreator.getNameBasedMd5(name);
```

I know that it wont affect your project anymore as you changed to `uuid.toString()`. But I want to express the change in my opinion due to other users who might think that the deprecation will be undone.

The objective is to fix a design mistake of mine while implementing the hash-based generators. Today they only exist to confuse the users of the library by adding lots almost duplicated methods.

Best regards.
